"""Batch A: context, architecture, component, deployment, AI, Messenger, tenant isolation."""
from dg2 import Graph


def context():
    g = Graph("context", 170, 112)
    g.node("sys", 85, 56, 46, 96, "ShopSathi\n\nAI sales agent for\nFacebook shops", "round", bold=True, fs=7.5)
    ys = [20, 56, 92]
    g.node("owner", 18, ys[0], 28, 18, "Shop owner", "box")
    g.node("mod", 18, ys[1], 28, 18, "Moderator", "box")
    g.node("cust", 18, ys[2], 28, 18, "Customer\n(Messenger user)", "box")
    g.node("adm", 152, ys[0], 28, 18, "Platform admin", "box")
    g.node("fb", 152, ys[1], 28, 18, "Facebook\n(Graph API,\nMessenger)", "box")
    g.node("llm", 152, ys[2], 28, 18, "OpenAI / Gemini\n(LLM, embeddings)", "box")
    g.edge("owner", "sys", "r", "l", "products, policy, staff,\nplan, Facebook link,\nreports", arrow="both", ob=-36)
    g.edge("mod", "sys", "r", "l", "inbox replies,\norders", arrow="both")
    g.edge("cust", "sys", "r", "l", "questions,\norder details,\nreplies", arrow="both", ob=36)
    g.edge("adm", "sys", "l", "r", "shops, plans,\nAI usage, health", arrow="both", ob=-36)
    g.edge("fb", "sys", "l", "r", "webhooks,\nsent replies", arrow="both")
    g.edge("llm", "sys", "l", "r", "prompts,\nanswers", arrow="both", ob=36)
    return g.save()


def system_architecture():
    g = Graph("sysarch", 170, 138)
    g.group(4, 4, 162, 24, "Clients")
    g.node("web", 40, 18, 52, 12, "Seller browser\n(Next.js dashboard)", "box")
    g.node("adm", 100, 18, 40, 12, "Admin browser\n(/admin pages)", "box")
    g.node("fb", 144, 18, 34, 12, "Facebook\nMessenger", "box")
    g.group(4, 34, 162, 26, "Edge")
    g.node("caddy", 85, 49, 84, 11, "Reverse proxy (Caddy, HTTPS) - production compose only", "box")
    g.group(4, 66, 162, 34, "Application")
    g.node("next", 28, 84, 40, 20, "Frontend\nNext.js 16\n(TypeScript, Tailwind)", "box")
    g.node("api", 80, 84, 48, 20, "Backend API\nFastAPI\n(routes, services)", "box")
    g.node("wk", 132, 84, 44, 20, "Worker\nCelery + beat\n(replies, embeddings, insights)", "box")
    g.group(4, 106, 162, 28, "Data and external services")
    g.node("pg", 28, 122, 40, 20, "PostgreSQL 16\n+ pgvector", "cyl")
    g.node("rd", 80, 122, 34, 20, "Redis\n(cache, locks,\nqueue)", "cyl")
    g.node("fs", 118, 122, 30, 14, "Photo storage\n(local disk)", "box")
    g.node("ai", 152, 117, 26, 9, "ai_engine", "box")
    g.node("llm", 152, 128, 26, 7, "OpenAI / Gemini", "box", dashed=True)
    g.edge("web", "caddy", "b", "t", None, ob=-30)
    g.edge("adm", "caddy", "b", "t", None, ob=10)
    g.edge("fb", "caddy", "b", "t", None, ob=34)
    g.edge("caddy", "next", "b", "t", "pages", oa=-40)
    g.edge("caddy", "api", "b", "t", "/api")
    g.edge("api", "wk", "r", "l", "queue", dashed=True)
    g.edge("api", "rd", "b", "t", None)
    g.edge("api", "pg", "b", "t", None, oa=-16)
    g.edge("api", "fs", "b", "t", None, oa=16)
    g.edge("wk", "ai", "b", "t", None, oa=12)
    g.edge("ai", "llm", "b", "t", None)
    return g.save()


def component():
    g = Graph("component", 170, 150)
    g.group(4, 4, 80, 56, "Frontend (Next.js)")
    for i, (k, t) in enumerate([("p1", "Auth pages"), ("p2", "Seller dashboard pages"), ("p3", "Admin pages"), ("p4", "Shared components\n(Inbox, ChatCards, PlanPicker...)"), ("p5", "API client (lib)")]):
        g.node(k, 44, 16 + i * 8.5 + (3 if i == 3 else 0) + (6 if i == 4 else 0), 70, 7.2 if i != 3 else 10, t, "box")
    g.group(90, 4, 76, 56, "API layer (routes)")
    g.node("r1", 128, 16, 66, 7, "auth, plans, shop, products", "box")
    g.node("r2", 128, 25, 66, 7, "test_chat, notifications, facebook", "box")
    g.node("r3", 128, 34, 66, 7, "chats, orders, reports", "box")
    g.node("r4", 128, 43, 66, 7, "admin, webhooks, health", "box")
    g.node("dep", 128, 53, 66, 6, "Dependencies: auth, role, tenant scope", "box", dashed=True)
    g.group(4, 66, 162, 42, "Services")
    names = ["conversation", "messenger_ingest", "messenger_processor", "facebook", "usage", "insights", "products /\nproduct_import", "embeddings", "chat_memory", "policy / plans /\nshop_deletion"]
    for i, t in enumerate(names):
        g.node(f"s{i}", 22 + (i % 5) * 31.5, 80 + (i // 5) * 14, 29, 11, t, "box", fs=6.0)
    g.group(4, 114, 78, 34, "Integrations and workers")
    g.node("i1", 24, 130, 34, 9, "Facebook graph_client,\nmessenger_sender", "box", fs=6.0)
    g.node("i2", 62, 130, 34, 9, "Celery tasks,\nai_adapters gateway", "box", fs=6.0)
    g.node("i3", 43, 142, 70, 6, "core: config, security, crypto, rate_limit, log_masking", "box", fs=5.8)
    g.group(88, 114, 78, 34, "Data and AI")
    g.node("d1", 108, 133, 32, 16, "Models (SQLAlchemy)\nPostgreSQL + pgvector", "box", fs=6.0)
    g.node("d2", 148, 133, 28, 16, "ai_engine\n(shopsathi_ai)", "box", fs=6.0)
    g.line([(84, 30), (90, 30)], arrow="both")
    g.line([(128, 60), (128, 66)], arrow="both")
    g.line([(43, 108), (43, 114)], arrow="both")
    g.line([(127, 108), (127, 114)], arrow="both")

    return g.save()


def deployment():
    g = Graph("deployment", 170, 128)
    g.group(4, 4, 74, 36, "Developer computer (local run)")
    g.node("l1", 24, 24, 32, 18, "uvicorn :8001\nCelery worker\nnext dev :3000", "box", fs=6.2)
    g.node("l2", 60, 24, 30, 18, "Docker: Postgres\n(pgvector) :5432\nRedis :6379", "box", fs=6.2)
    g.edge("l1", "l2", "r", "l")
    g.group(84, 4, 82, 36, "Test doubles used in local testing")
    g.node("t1", 106, 25, 36, 18, "scripts/fake_facebook\n(stands in for Graph API\nand Messenger)", "box", fs=6.0)
    g.node("t2", 146, 25, 30, 18, "Simulation script\n(signed webhook\nrequests)", "box", fs=6.0)
    g.group(4, 46, 162, 78, "Production compose stack (deploy/docker-compose.prod.yml), one server")
    g.node("u", 22, 66, 28, 12, "Browser", "box")
    g.node("caddy", 60, 66, 30, 12, "caddy\n:80 / :443", "box")
    g.node("fe", 100, 58, 34, 12, "frontend\nNext.js :3000", "box")
    g.node("api", 100, 76, 34, 12, "api\nFastAPI :8000", "box")
    g.node("wk", 144, 76, 34, 12, "worker\nCelery", "box")
    g.node("bt", 144, 58, 34, 12, "beat\nscheduler", "box")
    g.node("pg", 50, 106, 36, 20, "postgres\npgvector 16\n(named volume)", "cyl", fs=6.2)
    g.node("rd", 96, 106, 30, 20, "redis\n(named volume)", "cyl", fs=6.2)
    g.node("vol", 142, 106, 34, 14, "uploads volume\n(product photos)", "box", fs=6.2)
    g.edge("u", "caddy", "r", "l", "HTTPS")
    g.edge("caddy", "fe", "r", "l", None, via=[(78, 66), (78, 58)])
    g.edge("caddy", "api", "r", "l", None, via=[(78, 66), (78, 76)])
    g.edge("api", "pg", "b", "t", None, oa=-12)
    g.edge("api", "rd", "b", "t", None, oa=0, ob=-4)
    g.edge("wk", "rd", "b", "t", None, oa=-12, ob=8)
    g.edge("api", "vol", "r", "t", None, oa=2, via=[(122, 78), (122, 92), (142, 92)])
    g.edge("bt", "wk", "b", "t", None)
    return g.save()


def ai_architecture():
    g = Graph("ai_arch", 170, 150)
    g.node("in", 85, 8, 56, 8, "Customer message + chat memory (last 8 turns)", "box")
    g.node("lang", 85, 21, 56, 8, "1. Language detection (script and Banglish words)", "box")
    g.node("und", 85, 34, 56, 8, "2. Understanding (LLM, JSON): intent, entities, confidence", "box")
    g.node("hand", 85, 49, 46, 12, "3. Handover needed?\n(7 reasons)", "diamond", fs=6.2)
    g.node("ho", 150, 49, 30, 10, "Flag chat, pause AI,\nfixed safe reply", "box", fs=6.2)
    g.node("br", 85, 66, 56, 8, "4. Branch by intent", "box")
    g.node("ord", 24, 86, 40, 24, "Order branch\nextract_order (LLM)\ncode validates phone,\nstock, product", "box", fs=6.2)
    g.node("sug", 85, 86, 40, 24, "Suggestion branch\nneeds + budget (code)\nfilter live data,\nmax 3, stock > 0", "box", fs=6.2)
    g.node("fact", 146, 86, 40, 24, "Fact branch\nvector_search, search_products,\ncheck_stock,\nget_delivery_charge", "box", fs=6.2)
    g.node("rep", 85, 108, 70, 8, "5. Reply LLM writes the answer from verified facts only", "box")
    g.node("chk", 85, 119, 70, 8, "6. Grounding check (numbers, script); one retry; else fallback text", "box")
    g.node("out", 85, 131, 70, 8, "Reply, order draft or product cards -> saved and sent", "box")
    g.node("use", 146, 132, 32, 14, "ai_usage_logs\n(tokens, cost, time)", "cyl", fs=5.8)
    g.edge("in", "lang", "b", "t")
    g.edge("lang", "und", "b", "t")
    g.edge("und", "hand", "b", "t")
    g.edge("hand", "ho", "r", "l", "yes")
    g.edge("hand", "br", "b", "t", "no")
    g.edge("br", "ord", "b", "t", None, via=[(85, 72), (24, 72)])
    g.edge("br", "sug", "b", "t")
    g.edge("br", "fact", "b", "t", None, via=[(85, 72), (146, 72)])
    g.edge("ord", "rep", "b", "l", None, via=[(24, 108)])
    g.edge("sug", "rep", "b", "t")
    g.edge("fact", "rep", "b", "r", None, via=[(146, 108)])
    g.edge("rep", "chk", "b", "t")
    g.edge("chk", "out", "b", "t")
    g.edge("out", "use", "r", "l", "usage", dashed=True)
    return g.save()


def messenger_architecture():
    g = Graph("msgr_arch", 170, 118)
    g.node("cu", 20, 10, 30, 12, "Customer\n(Messenger)", "box")
    g.node("fb", 20, 40, 30, 14, "Facebook\nPlatform", "box")
    g.node("wh", 74, 40, 38, 22, "Webhook route\nGET: verify token\nPOST: check signature,\nparse events", "box", fs=6.0)
    g.node("ing", 118, 20, 38, 20, "messenger_ingest\nskip echo, find shop,\nde-duplicate by mid,\nsave message", "box", fs=6.0)
    g.node("q", 118, 54, 26, 14, "Redis queue\n(Celery)", "cyl", fs=6.0)
    g.node("proc", 118, 84, 38, 22, "messenger_processor\nlock per chat, checks,\nrun AI engine,\nsave reply", "box", fs=6.0)
    g.node("send", 62, 92, 38, 18, "MessengerSender\nSend API, retries,\n24-hour window", "box", fs=6.0)
    g.node("db", 154, 40, 28, 18, "PostgreSQL\nchats, messages,\norders", "cyl", fs=5.8)
    g.node("ai", 158, 84, 24, 12, "ai_engine", "box")
    g.node("sel", 20, 108, 30, 14, "Seller reply\n(Inbox, API)", "box", fs=6.0)
    g.edge("cu", "fb", "b", "t", "message")
    g.edge("fb", "wh", "r", "l", "POST +\nsignature")
    g.edge("wh", "ing", "r", "l", None, via=[(92, 40), (92, 20)])
    g.edge("ing", "db", "r", "t", None, via=[(147, 20), (154, 20)])
    g.edge("ing", "q", "b", "t", "enqueue")
    g.edge("q", "proc", "b", "t")
    g.edge("proc", "ai", "r", "l")
    g.edge("proc", "send", "l", "r")
    g.edge("send", "fb", "l", "b", "reply", oa=0, ob=8, via=[(28, 92)], label_at=0.7)
    g.edge("sel", "send", "r", "b", None)
    return g.save()


def tenant_isolation():
    g = Graph("tenant", 170, 100)
    g.node("tok", 24, 18, 40, 14, "JWT token\n(user id, role, shop_id)", "box", fs=6.2)
    g.node("dep", 70, 18, 40, 14, "get_current_user\nrole check", "box", fs=6.2)
    g.node("svc", 116, 18, 40, 14, "Service function\nreceives user.shop_id", "box", fs=6.2)
    g.node("scope", 152, 18, 30, 14, "scoped_select\nWHERE shop_id = ?", "box", fs=6.0)
    g.edge("tok", "dep", "r", "l")
    g.edge("dep", "svc", "r", "l")
    g.edge("svc", "scope", "r", "l")
    g.group(4, 42, 162, 50, "PostgreSQL")
    for i, (t, s) in enumerate([("Shop A", "products\nchats\norders"), ("Shop B", "products\nchats\norders")]):
        g.node(f"s{i}", 40 + i * 58, 74, 48, 28, f"{t}\n{s}", "box", fs=6.4)
    g.node("x", 148, 74, 34, 28, "Other shop's id\nin URL or body\n-> 404 Not found", "box", dashed=True, fs=6.0)
    g.edge("scope", "s0", "b", "t", "shop A rows only", via=[(152, 36), (60, 36)], ob=20, dashed=False, label_at=0.5)
    return g.save()


ALL = dict(context=context, sysarch=system_architecture, component=component, deployment=deployment, ai_arch=ai_architecture,
           msgr_arch=messenger_architecture, tenant=tenant_isolation)

if __name__ == "__main__":
    for k, f in ALL.items():
        print(f())
